### ISSUE TITLE
vnc error when multiple allocations?

### ISSUE THREAD

**Issue by jeremyfix** [jeremyfix/dcejs#12]
I got 2 users having a "cannot do something because it is null" like exception raised . 

The case was 2 allocations, one not successful because of QOS. 

These 2 users did not have tigervnc installed : does it matter ?

**Comment by jeremyfix** [comment]
Probably on mac , another user got :

Uncaught Exception:
TypeError: Cannot read property 'replace' of null
    at Socket.<anonymous> (/Applications/dcejs.app/Contents/Resources/app.asar/vnc.js:124:29)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

the issue is that vnc check for tigervnc on MacOS may return a null result on which we call replace in case tigervnc is not found.
